### PR TITLE
Js2

### PR DESCRIPTION
**Pull request by Phmik**
Adding our social platform for review. 

(Search function will come before final delivery)

### CODE REVIEW

**Comment by Fermain** [comment]
These comments are from a `manual` `end-to-end` test of this submission:

- UX, when updating a post it succeeds but the user is left stranded on the page.
- Meta, all pages have the same meta title. Not graded but easy to address.
- Search filter, does not seem to be working
- Look and feel, a wider column for smaller screens would be nice

Overall it seems like it's there, with only refinements to be made. A full review of the code will be done tomorrow AM.

**Comment by Phmik** [comment]
Added a confirm() on updating posts
Added search function

**Comment by Fermain** [comment]
I have added some fixes and suggestions in the `teacher-review` branch. Please check these out as an example for how to further improve your project.

**Review by Fermain — APPROVED** [review]
This is a good submission that meets the assessment requirements well. There is room for improvement in the code, however this mostly revolves around structure rather than the grasp of the language itself.

I suggest that you spend some time cleaning up the project, running a formatter such as prettier (you can install this to your package.json file and set it up as an `npm` command). Refactoring is a great way to better understand your own code, as the aim of the game is to delete code without changing functionality. This leaves your project smaller and easier to understand or change in future.

Well done, I enjoyed reviewing this.

**Pull request merged**
